# Nome do workflow
name: CI

# Quando o workflow será acionado
on:
  push:
    branches: [ main ]  # Executa no push para a branch main
  pull_request:
    branches: [ main ]  # Executa em PRs para a branch main
  workflow_dispatch:  # Permite execução manual

# Definição dos jobs
jobs:
  build:
    runs-on: ubuntu-latest  # Usa um ambiente Ubuntu

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3  # Obtém o código do repositório

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Define a versão do Node.js

      - name: Instalar dependências
        run: npm install  # Instala pacotes do package.json

      - name: Rodar testes
        run: npm test  # Executa testes com Jest, Mocha, etc.

      - name: Construir o projeto (se necessário)
        run: npm run build  # Apenas se houver um comando de build

      # - name: Publicar artefatos (opcional)
        # uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/  # Altere para o diretório gerado pelo build
