name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '16'  # Usa apenas o major version para evitar problemas futuros

      - name: Instalar dependências
        run: |
          cd src
          npm install

      - name: Executar testes
        run: npx mocha src/test/convert.js  # Evita instalação global do Mocha

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Construção da imagem Docker
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            alexanderba/aula-conversao-temperatura:{{github.run_number}}
            alexanderba/aula-conversao-temperatura:latest












# name: CI

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   # pull_request:
#   #   branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   # build:
#   CI:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
      
#       - name: setup NodeJs
#         uses: actions/setup-node@v4.2.0
#         with:
#           node-version: 16.13.2
          
#       - name: instalação mocha e do pacotes para testes
#         run: |
#           cd src
#           npm install -g mocha
#           npm install
          
#       - name: execução dos testes
#         run: mocha src/test/convert.js
        
#       - name: Docker Login
#         # You may pin to the exact commit or the version.
#         # uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
#         uses: docker/login-action@v3.4.0
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Construção da imagem Docker
#         uses: docker/build-push-action@v6.15.0
#         with:
#           context: ./src
#           file: ./src/Dockerfile  # Alterado de "src" para "file"
#           push: true
#           tags: |
#             alexanderba/aula-conversao-temperatura:v1
#             alexanderba/aula-conversao-temperatura:latest


#       # 
#       # # Runs a single command using the runner's shell
#       # - name: Run a one-line script
#       #   run: echo Hello, world!
#       #   # Runs a set of commands using the runner's shell
#       # - name: Run a multi-line script
#       #   run: |
#       #     echo Add other actions to build,
#       #     echo test, and deploy your project.
